# Form implementation generated from reading ui file 'd:\OneDrive\Hartberg\2022-23\8B WINF\Python\04 Login\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Login.resize(476, 295)
        Login.setModal(False)
        self.m_btnLogin = QtWidgets.QPushButton(Login)
        self.m_btnLogin.setGeometry(QtCore.QRect(60, 210, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.m_btnLogin.setFont(font)
        self.m_btnLogin.setDefault(True)
        self.m_btnLogin.setObjectName("m_btnLogin")
        self.label_3 = QtWidgets.QLabel(Login)
        self.label_3.setGeometry(QtCore.QRect(70, 20, 361, 41))
        font = QtGui.QFont()
        font.setFamily("KG Second Chances Solid")
        font.setPointSize(20)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(Login)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 90, 371, 37))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.m_tbUsername = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.m_tbUsername.setFont(font)
        self.m_tbUsername.setObjectName("m_tbUsername")
        self.horizontalLayout.addWidget(self.m_tbUsername)
        self.layoutWidget1 = QtWidgets.QWidget(Login)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 150, 371, 37))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.m_tbPassword = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.m_tbPassword.setFont(font)
        self.m_tbPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.m_tbPassword.setObjectName("m_tbPassword")
        self.horizontalLayout_2.addWidget(self.m_tbPassword)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.m_btnLogin.setText(_translate("Login", "Login"))
        self.label_3.setText(_translate("Login", "Login"))
        self.label.setText(_translate("Login", "Benutzername:"))
        self.label_2.setText(_translate("Login", "Passwort:"))
