# Form implementation generated from reading ui file 'd:\OneDrive\Hartberg\2022-23\8B WINF\Python\04 Login\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuAdministrator = QtWidgets.QMenu(self.menubar)
        self.menuAdministrator.setObjectName("menuAdministrator")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUser_hinzuf_gen = QtGui.QAction(MainWindow)
        self.actionUser_hinzuf_gen.setObjectName("actionUser_hinzuf_gen")
        self.menuAdministrator.addAction(self.actionUser_hinzuf_gen)
        self.menubar.addAction(self.menuAdministrator.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuAdministrator.setTitle(_translate("MainWindow", "Administrator"))
        self.actionUser_hinzuf_gen.setText(_translate("MainWindow", "User hinzufügen"))
